// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1AlOd6SS8OlzSCI7iSsFDNxoFSkzKVDs',
    appId: '1:919740602138:web:338d621645d322f9b8fea3',
    messagingSenderId: '919740602138',
    projectId: 'bellymax-35a4e',
    authDomain: 'bellymax-35a4e.firebaseapp.com',
    storageBucket: 'bellymax-35a4e.appspot.com',
    measurementId: 'G-X3TPKQ85MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24yoMcSliE0kCSQF97_uJgrkuKqDirIQ',
    appId: '1:919740602138:android:1ad46a906d0bfc6eb8fea3',
    messagingSenderId: '919740602138',
    projectId: 'bellymax-35a4e',
    storageBucket: 'bellymax-35a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYXXFjbc31y5FOoRvzkZTCnfrYBSXFhA',
    appId: '1:919740602138:ios:7ec07b6ea8161d94b8fea3',
    messagingSenderId: '919740602138',
    projectId: 'bellymax-35a4e',
    storageBucket: 'bellymax-35a4e.appspot.com',
    iosBundleId: 'com.example.bellymax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYXXFjbc31y5FOoRvzkZTCnfrYBSXFhA',
    appId: '1:919740602138:ios:7ec07b6ea8161d94b8fea3',
    messagingSenderId: '919740602138',
    projectId: 'bellymax-35a4e',
    storageBucket: 'bellymax-35a4e.appspot.com',
    iosBundleId: 'com.example.bellymax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1AlOd6SS8OlzSCI7iSsFDNxoFSkzKVDs',
    appId: '1:919740602138:web:45d701c35580bca4b8fea3',
    messagingSenderId: '919740602138',
    projectId: 'bellymax-35a4e',
    authDomain: 'bellymax-35a4e.firebaseapp.com',
    storageBucket: 'bellymax-35a4e.appspot.com',
    measurementId: 'G-QLXJ0PSC8W',
  );
}
