// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAwCvNP5lQppE2Y6GaqtDT28RC-IQbJJc',
    appId: '1:194562622028:web:b9fa35738e1f2852852ae9',
    messagingSenderId: '194562622028',
    projectId: 'qwibix-67080',
    authDomain: 'qwibix-67080.firebaseapp.com',
    storageBucket: 'qwibix-67080.appspot.com',
    measurementId: 'G-ZL9WD6832M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4jlTv8VdDFMp6PrITXuzLR1wq-ZxOcwE',
    appId: '1:194562622028:android:a9e69a2cabe62508852ae9',
    messagingSenderId: '194562622028',
    projectId: 'qwibix-67080',
    storageBucket: 'qwibix-67080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN7EcKM_RFHfH4v1nYirU4IoSdyHaQqqk',
    appId: '1:194562622028:ios:b008da3d311d3b77852ae9',
    messagingSenderId: '194562622028',
    projectId: 'qwibix-67080',
    storageBucket: 'qwibix-67080.appspot.com',
    iosBundleId: 'com.example.bellymax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN7EcKM_RFHfH4v1nYirU4IoSdyHaQqqk',
    appId: '1:194562622028:ios:b008da3d311d3b77852ae9',
    messagingSenderId: '194562622028',
    projectId: 'qwibix-67080',
    storageBucket: 'qwibix-67080.appspot.com',
    iosBundleId: 'com.example.bellymax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAwCvNP5lQppE2Y6GaqtDT28RC-IQbJJc',
    appId: '1:194562622028:web:e1c754369c85e799852ae9',
    messagingSenderId: '194562622028',
    projectId: 'qwibix-67080',
    authDomain: 'qwibix-67080.firebaseapp.com',
    storageBucket: 'qwibix-67080.appspot.com',
    measurementId: 'G-15J0B0WPY7',
  );

}